title: ☼Vox Uristi☼
description: Create beautiful renders of your Dwarf Fortress game
github_username: plule
minimal_mistakes_skin: dark
url: https://plule.github.io
baseurl: /vox-uristi
repository: plule/vox-uristi
logo: /assets/icon.png
include: ["_pages"]
compress_html:
  clippings: all
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
