title: ☼Vox Uristi☼
logo: /assets/icon.png
description: Create beautiful renders of your Dwarf Fortress game
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
