# Model configuration
# vox with the same name as the building are implied
buildings:
  Workshop/Tanners:
    model: Workshop/Craftsdwarfs.vox
  Bookcase:
    orientation: AgainstWall
    content: All
  Armorstand:
    orientation: AgainstWall
  Weaponrack:
    orientation: AgainstWall
  Bed:
    orientation: AgainstWall
  Cabinet:
    orientation: AgainstWall
  Coffin:
    model: Bed.vox
    orientation: AgainstWall
  Cabinet:
    orientation: AgainstWall
  Instrument:
    orientation: FacingChairOrAgainstWall
