# Model configuration
# vox with the same name as the building are implied
buildings:
  Workshop/*:
    is_floor: true
  Furnace/*:
    is_floor: true
  Statue:
    is_floor: true
  ScrewPump:
    is_floor: true
  Windmill:
    is_floor: true
  FarmPlot:
    is_floor: true
  Workshop/Tanners:
    model: Workshop/Craftsdwarfs.vox
  Bookcase:
    orientation: AgainstWall
    content: All
  Armorstand:
    orientation: AgainstWall
  Weaponrack:
    orientation: AgainstWall
  Bed:
    orientation: AgainstWall
  Cabinet:
    orientation: AgainstWall
  Coffin:
    model: Bed.vox
    orientation: AgainstWall
  Instrument:
    orientation: FacingChairOrAgainstWall
  Box:
    orientation: AgainstWall
  WindowGlass:
    connectivity: SelfOrWall
  WindowGem:
    connectivity: SelfOrWall
  Door:
    connectivity: SelfOrWall
  BarsVertical:
    connectivity: SelfOrWall
  Support:
    orientation: AgainstWall
  Floodgate:
    connectivity: SelfOrWall
  Table:
    connectivity: !SelfRemovesLayer 1
  TractionBench:
    model: Table.vox
    connectivity: !SelfRemovesLayer 1
